client_office/urls.py
from django.conf.urls import include, url
from . import views

from django.views.generic import ListView, DetailView
from master_office.views import OrderList, OrderDetailView

urlpatterns = [
    url(r'^$', 'client_office.views.client_page', name="client_page"),
    url(r'^current_orders/$', 'client_office.views.current_orders', name="current_clients_orders"),
    url(r'^orders/closed/$', 'client_office.views.closed_orders', name="clients_closed_orders"),
    url(r'^orders/(?P<pk>\d+)/$', 'client_office.views.order', name="client_office-detail"),

    url(r'^orders/(?P<pk>\d+)/addcomment/$', 'client_office.views.addcomment', name="addcomment"),

    url(r'^orders/(?P<pk>\d+)/add_feedback/$', 'client_office.views.add_feedback', name="add_feedback"),




# url(r'^my_orders/$', 'master_office.views.masters_orders', name="masters_orders"),
    # url(r'^my_closed_orders/$', 'master_office.views.masters_closed_orders', name="masters_closed_orders"),
    # url(r'^orders/take_order/(?P<pk>\d+)/$', 'master_office.views.take_order', name="take_order"),
    # url(r'^orders/close_order/(?P<pk>\d+)/$', 'master_office.views.close_order', name="close_order"),

    # # url(r'^orders/(?P<pk>\d+)/$', OrderDetailView.as_view(), name="master_orders-detail"),
    # # url(r'^add_comment/$', views.add_comment),

    # url(r'^orders/all_services/$', 'master_office.views.show_orderlines', name="orderlines"),
    # url(r'^orders/(?P<pk>\d+)/$', 'master_office.views.order', name="master_orders-detail"),
    # url(r'^orders/(?P<pk>\d+)/addcomment/$', 'master_office.views.addcomment', name="addcomment"),
    # # url(r'^orders/comment/(?P<article_id>[0-9]+)/$', views.add_comment, name='add_comment'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls), name="admin"),
    url(r'^', include('mainApp.urls')),
    url(r'^webexample/', include("webexample.urls")),
    url(r'^news/', include("news.urls")),
    url(r'^master/', include("master_office.urls")),
    url(r'^client/', include("client_office.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls import include, url
from django.views.generic import ListView, DetailView
from news.models import Articles

urlpatterns = [
    url(r'^$',
        ListView.as_view(queryset=Articles.objects.all().order_by('-date')[:20],template_name='news/posts.html'), name='news'),
    url(r'^(?P<pk>\d+)$',
        DetailView.as_view(model=Articles, template_name='news/post.html'))
]

# pk - primary key
# ?P - вместе обрабатывается
# \d - digital
# + - несколько цифр в числе

client_office/models.py
from django.db import models

# Create your models here.

master_office/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

from mainApp.models import Area, Service


class Master(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    photo = models.ImageField(upload_to='avatars/%Y/%m/%d/', default="")
    phone = models.CharField(max_length=20, default="")
    rating = models.FloatField(default=0)
    areas = models.ManyToManyField(Area)

    def __str__(self):
        return self.user.username

    def get_user(self):
        return self.user.last_name + " " + self.user.first_name

    def get_areas(self):
        return "".join([a.name for a in self.areas.all()])


class Order(models.Model):
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.IntegerField(default=0)
    price = models.FloatField()
    begin_date = models.DateTimeField(auto_now=True)
    end_date = models.DateTimeField(blank=True, null=True)
    expected_date = models.DateTimeField(blank=True, null=True)
    rating = models.IntegerField(default=0, blank=True, null=True)
    feedback = models.TextField(blank=True, null=True)

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('master_orders-detail', args=[str(self.id)])

    def get_client(self):
        return self.client.last_name + " " + self.client.first_name


class OrderLine(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    master = models.ForeignKey('Master', on_delete=models.CASCADE, blank=True, null=True)
    brand_name = models.CharField(max_length=20)
    device_name = models.CharField(max_length=20)
    serial_id = models.CharField(max_length=20)
    feedback = models.TextField(blank=True, null=True)
    trouble_description = models.TextField()
    status = models.IntegerField(default=0)

    def __str__(self):
        return self.feedback

    def get_absolute_url(self):
        return reverse('orders')

    def get_master(self):
        if self.master is None:
            res = "No master"
            print("no master")
        else:
            res = self.master.last_name + " " + self.master.first_name
        return res


class Comment(models.Model):
    content = models.TextField(verbose_name="Текст комментария")
    author = models.ForeignKey(User, null=True)
    order = models.ForeignKey(Order)
    date = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.content

client_office/forms.py
from django import forms
from django.contrib.auth.models import User

from master_office.models import Order


class FeedbackForm(forms.ModelForm):
    feedback = forms.CharField(label="Отзыв о качестве работы", required=True)
    rating = forms.IntegerField(label="Оценка", required=True, max_value=5, min_value=0)

    class Meta:
        model = Order
        fields = ('feedback', 'rating')

    def save(self, commit=True):
        order = super(forms.ModelForm, self).save(commit=False)
        order.feedback = self.cleaned_data["feedback"]
        order.rating = self.cleaned_data["rating"]
        # comment. = self.cleaned_data["first_name"]
        # user.last_name = self.cleaned_data["last_name"]
        if commit:
            order.save()
        return order

client_office/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User

from client_office.forms import FeedbackForm
from master_office.forms import CommentForm
from master_office.models import Order, Comment, Master, OrderLine


def client_page(request):
    args = {}
    args['user'] = request.user
    return render(request, 'client_office/client_page.html', args)


def current_orders(request):
    user = request.user
    args = {}
    args['user'] = user
    args['orders'] = Order.objects.filter(client_id=user.pk).filter(status=0)
    args['title'] = "Текущие заказы"
    return render(request, 'client_office/current_orders.html', args)


def order(request, pk=1):
    comment_form = CommentForm()
    args = {}
    # args.update(csrf(request))
    order = Order.objects.get(id=pk)
    args['order'] = order
    args['comments'] = Comment.objects.filter(order=args['order'])
    args['username'] = request.user
    if order.status == 1:
        fb_form = FeedbackForm()
        args['fb_form'] = fb_form
    else:
        args['form'] = comment_form

    return render(request, 'client_office/order_detail.html', args)


def closed_orders(request):
    user = request.user
    args = {}
    args['user'] = user
    args['orders'] = Order.objects.filter(client_id=user.pk).filter(status=1)
    args['title'] = "Закрытые заказы"

    return render(request, 'client_office/current_orders.html', args)


def add_feedback(request, pk):
    args = {}
    # args.update(csrf(request))
    args['order'] = Order.objects.get(id=pk)
    args['comments'] = Comment.objects.filter(order=args['order'])
    args['username'] = request.user

    fb_form = FeedbackForm()
    args['fb_form'] = fb_form
    if request.POST:
        fb_form = FeedbackForm(request.POST)
        args['fb_form'] = fb_form
        if fb_form.is_valid():
            form_res = fb_form.save(False)
            cur_order = Order.objects.get(id=pk)
            cur_order.feedback = form_res.feedback
            cur_order.rating = form_res.rating
            cur_order.save()
            args['ready'] = 'Спасибо за вашу оценку! Вы помогаете нам стать лучше!'
            args['fb_form'] = FeedbackForm()
            lines = OrderLine.objects.filter(order=cur_order)
            for l in lines:
                masters_line = OrderLine.objects.filter(master=l.master).filter(status=1)
                m_rating = 0
                m_qty = 0
                for ml in masters_line:
                    m_rating += ml.order.rating
                    m_qty += 1
                l.master.rating = m_rating / m_qty
                l.master.save()
                print(l.master)
                print(m_rating / m_qty)
            return render(request, 'client_office/order_detail.html', args)

    return render(request, 'client_office/order_detail.html', args)


def addcomment(request, pk):
    if request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.rating = 0
            comment.author = request.user
            comment.order = Order.objects.get(id=pk)
            form.save()
            return redirect('client_office-detail', pk=pk)
            # return HttpResponseRedirect('/')
    else:
        form = CommentForm()
    return render(request, 'registration/register.html', {'form': form})

client_office/templates/client_office/client_page.html
{% extends "client_office/client_wrapper.html" %} {% block client_content %}
<div class="page">
    <h1>{{user.last_name}} {{user.first_name}} </h1>
    <h1>{{user.email}} </h1>
</div>
{% endblock %}

client_office/templates/client_office/client_wrapper.html
{% extends "mainApp/wrapper.html" %} {% block content %}
<div class="menu-buttons">
    <a href="{% url 'client_page' %}">Кабинет клиента</a></li>
    <a href="{% url 'current_clients_orders' %}">Текущие заказы</a></li>
    <a href="{% url 'clients_closed_orders' %}">Закрытые заказы</a></li>
</div>
<hr class="hr-green"> 
{% block client_content %} {% endblock %} {% endblock %}

client_office/templates/client_office/current_orders.html
{% extends "client_office/client_wrapper.html" %}

{% block client_content %}
    <h4 class="area-text-primary">{{ title }}</h4>
    <div class="orders">
        {% for order in orders %}
            <hr class="hr-small">
            <a class="area-text-primary" href="{% url 'client_office-detail' order.pk %}"><h3>{{ order.pk }}</h3></a>
        {% endfor %}
    </div>
{% endblock %}

client_office/templates/client_office/order_detail.html
{% extends "client_office/client_wrapper.html" %}

{% block client_content %}
<div class="order">
    {% if ready %}
            <div class="order-ready">
                <h4>{{ ready }}</h4>
            </div>
    {% endif %}
    
    Информация о заказе:
    <p>Статус заказа: {{ order.status }}</p>
    <p>Клиент: {{ order.client.first_name }}</p>
    <p>Цена: {{ order.price }}</p>
    <p>Обратная связь: {{ order.feedback }}</p>
    <hr>
    {% for line in order.orderline_set.all %}
        <p>Название услуги: {{ line.service.name }}</p>
        <p>Описание проблемы: {{ line.touble_description }}</p>
        <p>brand: {{ line.brand_name }}</p>
        <hr>
    {% endfor %}

    {% if fb_form != Null %}
        <p>Оцените заказ!</p>
        <form action="{% url 'add_feedback' order.id %} " method="post">

    <h4>Ваша текущая оценка: {{ order.rating }} </h4>
    <h4>Ваш текущий отзыв: {{ order.feedback }}</h4>
            {% csrf_token %}
            {{ fb_form.as_p }}
            <button class="button" type="submit">Оценить</button>
        </form>
    {% endif %}


    <p>Комментарии:</p>
    {% if form != Null %}

        <form action="{% url 'addcomment' order.id %} " method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="button" type="submit">Добавить комментарий</button>
        </form>
    {% endif %}
    {% for comment in order.comment_set.all %}
        <hr>
        <p>Текст комментария: {{ comment.author.username }}</p>
        <p>Автор комментария: {{ comment.content }}</p>
    {% endfor %}
</div>

{% endblock %}