mainApp/urls.py
from django.conf.urls import include, url
from . import views

from django.views.generic import ListView, DetailView
from mainApp.models import Area
from mainApp.views import AreaList, AreaDetailView, ServiceDetailView, MasterList, MasterDetailView

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^register/$', views.register_user, name="register"),

    url(r'^masters/$', MasterList.as_view(), name="masters"),
    url(r'^masters/(?P<pk>\d+)$', MasterDetailView.as_view(), name="masters-detail"),

    url(r'^feedback/$', views.get_feedback, name="last_feedback"),

    url(r'^areas/$', AreaList.as_view(), name="areas"),
    url(r'^areas/(?P<pk>\d+)$', AreaDetailView.as_view(), name="areas-detail"),
    url(r'^areas/service/(?P<pk>\d+)/$', ServiceDetailView.as_view(), name="service-detail"),
    url(r'^areas/service/(?P<pk>\d+)/make_order/', views.make_order, name="make_order"),

    url(r'^area/create/$', views.AreaCreate.as_view(), name='area-create'),
    url(r'^area/(?P<pk>\d+)/update/$', views.AreaUpdate.as_view(), name='area-update'),
    url(r'^area/(?P<pk>\d+)/delete/$', views.AreaDelete.as_view(), name='area-delete'),

    url(r'^add_comment/(?P<pk>\d+)/$', views.add_comment, name=""),

    url(r'^statistics/$', views.statistics, name="statistics"),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls), name="admin"),
    url(r'^', include('mainApp.urls')),
    url(r'^webexample/', include("webexample.urls")),
    url(r'^news/', include("news.urls")),
    url(r'^master/', include("master_office.urls")),
    url(r'^client/', include("client_office.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls import include, url
from django.views.generic import ListView, DetailView
from news.models import Articles

urlpatterns = [
    url(r'^$',
        ListView.as_view(queryset=Articles.objects.all().order_by('-date')[:20],template_name='news/posts.html'), name='news'),
    url(r'^(?P<pk>\d+)$',
        DetailView.as_view(model=Articles, template_name='news/post.html'))
]

# pk - primary key
# ?P - вместе обрабатывается
# \d - digital
# + - несколько цифр в числе

mainApp/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Area(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField()
    photo = models.ImageField(upload_to='areas/', default="")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('areas-detail', args=[str(self.id)])


class Service(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField()
    time = models.CharField(max_length=20, help_text="How much time service will take")
    price = models.IntegerField()
    area = models.ForeignKey('Area', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('service-detail', args=[str(self.id)])

mainApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from master_office.models import OrderLine, Order, Service
from django.forms import inlineformset_factory
from django.contrib.auth.models import Group


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(label='Имя', max_length=100)
    last_name = forms.CharField(label='Фамилия', max_length=100)
    error_css_class = 'error'
    required_css_class = 'required'

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2", "first_name", "last_name")

    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        if commit:
            user.save()
        return user


class OrderLineForm(forms.ModelForm):
    service = forms.ModelChoiceField(queryset=Service.objects.all(), required=True, label="Услуга")
    brand_name = forms.CharField(label="Брэнд", max_length=20)
    device_name = forms.CharField(label="Модель", max_length=20)
    serial_id = forms.CharField(label="Серийный номер", max_length=20)
    trouble_description = forms.CharField(widget=forms.Textarea, label="Описание проблемы", max_length=100)

    class Meta:
        model = OrderLine
        fields = ['service', 'brand_name', 'device_name', 'serial_id', 'trouble_description']

    def save(self, commit=False):
        line = super(forms.ModelForm, self).save(commit=False)
       # line.service = self.serice
        if commit:
            line.save()
        return line

mainApp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from master_office.forms import CommentForm
from master_office.views import OrderDetailView
from news.models import Articles
from mainApp.forms import UserRegisterForm, OrderLineForm
from django.http import HttpResponseRedirect
from master_office.models import Order, OrderLine, Master
from django.forms.formsets import formset_factory


def index(request):
    num_categories = Area.objects.all().count()
    num_articles = Articles.objects.all().count()
    num_instances_available = Articles.objects.filter(author__exact='kate').count()
    return render(
        request,
        'mainApp/home.html',
        context={'num_categories': num_categories, 'num_articles': num_articles,
                 'num_instances_available': num_instances_available},
    )


def statistics(request):
    args = {}
    all_areas = []
    a = 0
    areas = Area.objects.all()
    for area in areas:
        orders = OrderLine.objects.filter(status=1).filter(service__area=area).count()
        area_info = []
        area_info.append(area.name)
        area_info.append(orders)
        all_areas.append(area_info)
        print(area_info)
        a += 1

    args['areas'] = all_areas


    print(args)
    return render(request, 'mainApp/statistics.html', context=args)


def contact(request):
    return render(request, 'mainApp/basic.html')


def get_feedback(request):
    orders = Order.objects.filter(status=1).exclude(feedback__isnull=True).order_by('-end_date')
    return render(request, 'mainApp/feedback.html', context={'orders': orders})


def register_user(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            #     group = Group.objects.get(name='ServiceClient')
            #     user.groups.add(group)
            #     # form.save()
            #     # user.groups.add(group)
            #     # user.groups.add(1) # add by id
            # # /group.user_set.add(user)
            #     user.save()
            return HttpResponseRedirect('/')
    else:
        form = UserRegisterForm()

    return render(request, 'registration/register.html', {'form': form})


# g = Group.objects.get(name='My Group Name')
# users = User.objects.all()
# for u in users:
#     g.user_set.add(u)


from django.views.generic import ListView
from django.views.generic.detail import DetailView
from mainApp.models import Area, Service


class AreaList(ListView):
    model = Area


class ServiceDetailView(DetailView):
    model = Service


class AreaDetailView(DetailView):
    model = Area


class MasterList(ListView):
    model = Master


class MasterDetailView(DetailView):
    model = Master


def book_detail_view(request, pk):
    try:
        book_id = Area.objects.get(pk=pk)
    except Area.DoesNotExist:
        raise Http404("Area does not exist")

    # book_id=get_object_or_404(Area, pk=pk)

    return render(
        request,
        'catalog/book_detail.html',
        context={'book': book_id, }
    )


@login_required
def make_order(request, pk):
    OrderLineFormSet = formset_factory(OrderLineForm, extra=0, can_delete=True)
    if request.method == 'POST':
        formset = OrderLineFormSet(request.POST)
        if formset.is_valid():
            order = Order()
            order.client = request.user
            order.price = 0
            order.save()
            print()
            for form in formset:

                if form.is_valid():
                    order_line = form.save(commit=False)
                    print("hi")
                    if order_line:
                        print(True)
                        order_line.order = order
                        order_line.feedback = "1"
                        order_line.price = order_line.service.price
                        form.save(commit=True)
                    else:
                        print(False)

            all_lines_in_order = OrderLine.objects.filter(order=order)
            total_price = 0
            for one_line in all_lines_in_order:
                total_price = total_price + one_line.service.price
            order.price = total_price
            order.save()
            # lines = formset.save(commit=False)
            # for line in lines:
            #     line.order = order
            #     line.save()
            # line = form.save(False)
            # line.order = order
            # line.feedback = ""
            # form.save()
            ready = "Благодарим за оформление заказа! Заказ зарезервирован!"
            service = Service.objects.get(pk=pk)
            formset = OrderLineFormSet(initial=[{'service': service}])
            return render(request, 'mainApp/temp.html', {'formset': formset, 'ready': ready})
    else:
        service = Service.objects.get(pk=pk)
        formset = OrderLineFormSet(initial=[{'service': service}])
    return render(request, 'mainApp/temp.html', {'formset': formset})

    # OrderLineFormSet = formset_factory(OrderLineForm)
    # formset = OrderLineFormSet()
    # if request.POST:
    #     if formset.is_valid():
    #         print("valid")
    #         order = Order()
    #         order.client = request.user
    #         order.price = 0
    #         order.save()
    #         # if formset.is_valid():
    #         for form in formset:

    #             if form.is_valid():
    #                 order_line = form.save(commit=False)
    #                 order_line.order = order
    #                 form.save()

    #     # orderLines = formset.save(commit=False)
    #     # else: formset.errors
    # else:
    #     print("novalid")
    #     print(formset.errors)
    #     messages.success(request, "Payments saved successfully")
    # return render(request, "mainApp/temp.html", {"formset": formset})


#     args['order'] = Order.objects.get(id=pk)
#     args['comments'] = Comment.objects.filter(order=args['order'])
#     args['form'] = comment_form
#     args['username'] = request.user
# class Order(models.Model):
#     client = models.ForeignKey(User, on_delete=models.CASCADE)
#     status = models.IntegerField(default = 0)
#     price = models.FloatField()
#     begin_date = models.DateTimeField(auto_now=True)
#     end_date = models.DateTimeField(blank=True)
#     expected_date = models.DateTimeField(blank=True)
#     rating = models.IntegerField(default = 0, blank=True)
#     feedback = models.TextField(blank=True)

# class OrderLine(models.Model):
#     order = models.ForeignKey('Order', on_delete=models.CASCADE)
#     service = models.ForeignKey(Service, on_delete=models.CASCADE)
#     master = models.ForeignKey('Master', on_delete=models.CASCADE, blank=True)
#     brand_name = models.CharField(max_length = 20)
#     device_name = models.CharField(max_length = 20)
#     serial_id = models.CharField(max_length = 20)
#     feedback = models.TextField(blank=True)
#     trouble_description = models.TextField()
#     status = models.IntegerField(default = 0)


@login_required
def add_comment(request):
    OrderDetailView.as_view()
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = CommentForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/')


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Area


class OrderLineCreate(CreateView):
    model = OrderLine
    fields = '__all__'


class AreaCreate(CreateView):
    model = Area
    fields = '__all__'
    # initial={'date_of_death':'12/10/2016',}


class AreaUpdate(UpdateView):
    model = Area
    fields = '__all__'
    # ['first_name','last_name','date_of_birth','date_of_death']


class AreaDelete(DeleteView):
    model = Area
    success_url = reverse_lazy('areas')


def do(self, **kwargs):
    print("1")
    return "1"

mainApp/templates/mainApp/area_confirm_delete.html
{% extends "mainApp/wrapper.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the area: {{ area }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

mainApp/templates/mainApp/area_detail.html
{% extends "mainApp/wrapper.html" %} {% block content %}
<div class="text-container-center">
    <div class="wrap">
        <h2 class="area-text-primary">{{area.name}} </h2>
        <h4 class="area-text-description">{{area.description|safe|linebreaks}} </h4>
        <hr>
        <div class="area-container">
            {% for service in area.service_set.all %}
            <div class="area-link-item">
                <a class="area-link" href="{% url 'service-detail' service.pk %}">{{ service.name }}</a>
            </div>
            {% endfor %}
        </div>
        {% for i in user.groups.values_list %} {% if "ServiceMaster" in i %}
        <div class="area-categories">
            <hr>
            <div class="crud-item"><a class="area-link-crud" href="{% url 'area-create' %}">Добавить категорию</a></div>
            <div class="crud-item"><a class="area-link-crud" href="{% url 'area-update' area.pk %}">Редактировать категорию</a></div>
            <div class="crud-item"><a class="area-link-crud" href="{% url 'area-delete' area.pk %}">Удалить категорию</a></div>
        </div>
        {% endif %} {% endfor %}
    </div>
</div>
{% endblock %}

mainApp/templates/mainApp/area_form.html
{% extends "mainApp/wrapper.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

mainApp/templates/mainApp/area_list.html
{% extends "mainApp/wrapper.html" %} {% load static %} {% block content %} {% for area in object_list %}
<div class="area-item">
    <a href="{% url 'areas-detail' area.pk %}">
        <div class="portfolio web" data-cat="web">
            <div class="portfolio-wrapper">
                <div class="portfolio-img"><img src={{area.photo.url}} alt="Area image" /></div>
                <div class="label">
                    <div class="label-text">
                        <p class="text-title">{{ area.name }}</p>
                        <span class="text-category">{{ area.description }}</span>
                    </div>
                    <div class="label-bg"></div>
                </div>
            </div>
        </div>
    </a>
</div>
{% endfor %} {% endblock %}

mainApp/templates/mainApp/basic.html
{% extends "mainApp/wrapper.html" %} {% load static %} {% block content %}
<script type="text/javascript">
ymaps.ready(init);
        var myMap, 
            myPlacemark;

        function init(){ 
            myMap = new ymaps.Map("map", {
                center: [53.91793482, 27.59475116],
                zoom: 14
            }); 
            
            myPlacemark = new ymaps.Placemark([53.91793482, 27.59475116], {
                hintContent: 'Tech Service',
                balloonContent: 'Лучший сервис в мире'
            });
            
            myMap.geoObjects.add(myPlacemark);
        }
</script>
</div>
 
<div class="text-container-center"><div id="map"></div>
<div class="way" >
     <h1>ПРИГЛАШАЕМ ПОСЕТИТЬ НАШ ФИРМЕННЫЙ МАГАЗИН И ЦЕНТР СЕРВИСНОГО ОБСЛУЖИВАНИЯ ПО АДРЕСУ:</h1>
     <br>
     <p> Г. МИНСК, УЛ. ПЕТРУСЯ БРОВКИ, 6. (выход из метро в сторону Комаровского рынка; рядом с нами торговый центр Импульс и магазин Fashion Outlet)</p>
     <br>
     <h1>CПРАВОЧНАЯ СЛУЖБА СЕРВИСНОГО ЦЕНТРА</h1>
    <p>
        <span>8 029 212 89 66</span>
        <br>
        <span>8 025 900 09 09</span>
        <br>
        <span>8 029 334 09 09</span>
    </p>
</div>
{% endblock %}

mainApp/templates/mainApp/feedback.html
{% extends "mainApp/wrapper.html" %} {% block content %} {% load static %}
<div class="order">
    <p class="area-text-primary">Наши отзывы</p>
    {% for order in orders %}
        <hr>
        <h4>Заказ: </h4>
        <h4>Оценка: {{ order.rating }}</h4>
        <h4>Автор: {{ order.client.username }}</h4>
        <h4>Отзыв: {{ order.feedback }}</h4>
    {% endfor %}
</div>
{% endblock %}

mainApp/templates/mainApp/home.html
{% extends "mainApp/wrapper.html" %} {% block content %} {% load static %}
<div class="describe">
    <div class="h_left">
        <h2>Хотите справляться со всеми задачами быстро и эффективно? Тогда Вы зашли на правильную страничку, ведь  Tech Service знает, как разрешать любые поручения в минимальные сроки. Перечень наших услуг огромен, мы можем практически все!</h2>
        <br>
        <div class="devices"><img src="{% static 'images/devices.png' %}" alt="devices"></div>
        <br>
        <br>
        <br>
        <h2>Прежде чем приступить к ремонту, наши мастера осуществляют обязательную диагностику телевизоров, выявляют причину поломки и озвучивают Вам стоимость работ. Только после Вашего согласия мы приступаем к ремонту. В этом случае диагностика и доставка будет бесплатной. В случае если Вас не устаивает цена ремонта или ремонт оказался не целесообразным, Вам необходимо будет оплатить доставку техники до Вашего дома.</h2>
        <div class="devices"><img src="{% static 'images/iphone.png' %}" alt="devices"></div>
    </div>
</div>
{% endblock %}

mainApp/templates/mainApp/orderline_form.html
{% extends "mainApp/wrapper.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

mainApp/templates/mainApp/service_detail.html
{% extends "mainApp/wrapper.html" %} {% block content %}
<div class="text-container-center">
    <h1 class="area-text-primary">РЕМОНТ {{service.name}}</h1>
    <h5 class="area-text-description">{{service.description}}</h5>
    <div class="time-price">
        <h5>Время выполнения: {{service.time}}</h5>
        <h5>Стоимость: {{service.price}}</h5>
    </div>
    <hr>
    <div class="area-button">
        <a href="{% url 'areas-detail' service.area.id %}" class="btn btn-primary">Вернуться к категории</a>
    </div>
    <div class="area-button">
        <a href="{% url 'make_order' service.pk %}" class="btn btn-primary">Оформить заказ</a>
    </div>
</div>
{% endblock %}

mainApp/templates/mainApp/statistics.html
{% extends "mainApp/wrapper.html" %} {% block content %} {% load static %}
    <div class="order">

        <div id="air" style="width: 800px; height: 800px; margin: auto; margin-top: -100px; "></div>


        <script src="https://www.google.com/jsapi"></script>
        <script>
            google.load("visualization", "1", {packages: ["corechart"]});
            google.setOnLoadCallback(drawChart);

            function drawChart() {
                var array = {{ areas|safe}};
                console.log(array[0]);

                var data = google.visualization.arrayToDataTable([
                    ['Категория ремонта', 'Кол-во выполненных заказов'],
                    [array[0][0], array[0][1]],
                    [array[1][0], array[1][1]],
                    [array[2][0], array[2][1]],
                    [array[3][0], array[3][1]],
                    [array[4][0], array[4][1]]
                ]);

                var options = {
                    title: 'Отремонтированная техника',
                    is3D: true,
                    pieResidueSliceLabel: 'Остальное'
                };
                var chart = new google.visualization.PieChart(document.getElementById('air'));
                chart.draw(data, options);
            }
        </script>
    </div>
{% endblock %}

mainApp/templates/mainApp/temp.html
{% extends "mainApp/wrapper.html" %}

{% block content %}
    
    {% if ready %}
        <h3 class="order-ready">{{ ready }}</h3>
    {% endif %}

    <div class="text-container-center">
        <h3 class="area-text-primary">Оформление заказа</h3>
        <form action="" method="post">
    
            {% csrf_token %}
    
            {{ formset.management_form }}
            <div id="form_set">
                {% for one_form in formset %}
                    <table class='no_error'>
                        {{ one_form.as_table }}
                    </table>
                {% endfor %}
            </div>
            <input class="register-button" type="button" value="Добавить услугу" id="add_more">
            <div id="empty_form" style="display:none">
                <table class='no_error'>
                    {{ formset.empty_form.as_table }}
                </table>
            </div>
            <script>
                $('#add_more').click(function () {
                    var form_idx = $('#id_form-TOTAL_FORMS').val();
                    $('#form_set').append($('#empty_form').html().replace(/__prefix__/g, form_idx));
                    $('#id_form-TOTAL_FORMS').val(parseInt(form_idx) + 1);
                });
            </script>
            <input id="register-button" type="submit" value="Оформить заказ"/>
    
        </form>
    {% endblock %}</div>

mainApp/templates/mainApp/wrapper.html
<!DOCTYPE HTML>
<html>

<head>
    <title>Tech Service</title>
    {% load static %}
    <link rel="icon" href="static/images/heart.png" type="image/x-icon">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Gaegu" rel="stylesheet">
    <link rel='stylesheet' href="{% static 'css/style.css' %}" type='text/css'>
    <!--  jquery plguin -->
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <!-- start gallery -->
    <script type="text/javascript" src="{% static 'js/headhesive.min.js' %}"></script>
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript">
    </script>
    <script type="text/javascript">
        $(function () {
            var header = new Headhesive('.header');
            var filterList = {

                init: function () {

                    // MixItUp plugin
                    // http://mixitup.io
                    $('#portfoliolist').mixitup({
                        targetSelector: '.portfolio',
                        filterSelector: '.filter',
                        effects: ['fade'],
                        easing: 'snap',
                        // call the hover effect
                        onMixEnd: filterList.hoverEffect()
                    });

                },

                hoverEffect: function () {
                    // Simple parallax effect
                    $('#portfoliolist .portfolio').hover(
                        function () {
                            $(this).find('.label').stop().animate({bottom: 0}, 200, 'easeOutQuad');
                            $(this).find('img').stop().animate({top: -30}, 500, 'easeOutQuad');
                        },
                        function () {
                            $(this).find('.label').stop().animate({bottom: -40}, 200, 'easeInQuad');
                            $(this).find('img').stop().animate({top: 0}, 300, 'easeOutQuad');
                        }
                    );
                }
            };

            // Run the show!
            filterList.init();

        });
    </script>
    <!-- Add fancyBox main JS and CSS files -->
</head>

<body>
<!-- start header -->
<div class="header_bg">
    <div>
        <div class="header">
            <div class="logo">
                <h1 id="logo"><a class="link" href="{% url 'index' %}">Tech Service</a></h1>
            </div>
            <div class="h_right">
                <ul class="menu">
                    <li class="menu-item"><a href="{% url 'areas' %}">Категории</a></li>
                    <li class="menu-item"><a href="{% url 'masters' %}">Мастера</a></li>
                    <li class="menu-item"><a href="/contact">Контакты</a></li>
                    <li class="menu-item"><a href="{% url 'last_feedback' %}">Oтзывы</a></li>

                    {% if user.groups.values_list|length == 0 and user.is_authenticated  %}
                        <li class="menu-item"><a href="{% url  'client_page' %}">Кабинет пользователя</a></li>
                    {% endif %}

                    {% for i in user.groups.values_list %}
                        {% if "ServiceAdmin" in i %}
                            <li class="menu-item"><a href="/admin">Админ</a></li>
                        {% elif "ServiceMaster" in i %}
                            <li class="menu-item"><a href="{% url 'master_page' user.pk %}">Кабинет мастера</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if user.is_authenticated %}
                        <li class="non-clickable">Вы вошли как: {{ user.get_username }}</li>
                        <li class="menu-item logout"><a href="{% url 'logout' %}?next=/">Выйти</a></li>
                    {% else %}
                        <li class="menu-item">
                            <a href="{% url 'login' %}">
                                Войти</a>
                        </li>
                        <li class="menu-item"><a
                                href="{% url 'register' %}?next={{ request.path }}">Зарегистрироваться</a></li>
                    {% endif %}
                </ul>
                <script type="text/javascript" src="{% static 'js/responsive.menu.js' %}"></script>
                <!-- end smart_nav * -->
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>
<!-- start main -->
<div id="main">
    {% block content %} {% endblock %}
</div>
<!-- footer -->
    <div class="footer_bg">
        <div class="footer">
            <div class="wrap">
                <div class="span_of_4">
                    <div class="span1_of_4">
                        <h4>о нас</h4>

                        <p>Наша компании «TECH SERVICE» оказывает услуги по настройке и ремонту любого вида техники в
                            Минске и в Минской области.</p>
                        <span>Адрес</span>
                        <p class="top">ул. Петруся Бровки 6,</p>
                        <p>БГУИР Корпус №1</p>
                        <p>г. Минск</p>
                        <p>Phone:(29) 212 89 66</p>
                        <p>E-mail: roman311297@gmail.ru</p>
                        <div class="f_icons">
                            <ul>
                                <li><a class="icon2" href="https://twitter.com/ebsuir"></a></li>
                                <li><a class="icon1" href="https://www.facebook.com/"></a></li>
                                <li><a class="icon3" href="https://mail.google.com/mail/u/0/#inbox"></a></li>
                                <li><a class="icon4" href="https://github.com/justmad1/techService"></a></li>
                                <li><a class="icon5" href="http://127.0.0.1:8000"></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="span1_of_4">
                        <h4>Поддержка</h4>
                        <ul>
                            <li>
                                <a href="{% url 'statistics' %}"><span>Статистика</span></a>
                            </li>
                            <li>
                                <a href="https://tech.onliner.by/tag/it-belarus"><span>Главные новости</span></a>
                            </li>
                            <li>
                                <a href="/areas"><span>Оформить услугу</span></a>
                            </li>
                            <li>
                                <a href="/contact"><span>Наш сервис</span></a>
                            </li>
                            <li>
                                <a href="https://www.google.by/search?biw=1707&bih=816&tbm=isch&sa=1&ei=R5H6WrVJxpeyAYqkjoAL&q=atari+breakout+&oq=atari+breakout+&gs_l=img.3..0l10.5251.5694.0.6853.3.3.0.0.0.0.283.626.0j2j1.3.0....0...1.1.64.img..0.1.283....0.oLbYA-7FqGY"><span>Скоротать время</span></a>
                            </li>
                        </ul>
                    </div>
                    <div class="span1_of_4">
                        <h4>Наши достижения и победы</h4>
                        <ul>
                            <li>
                                <a href="http://atrsib.ru/index.php/konkursy/pobediteli-konkursov/nominatsiya-luchshij-biznes-proekt">
                                    <span>Номинация «Лучший бизнес-проект» 2000</span></a></li>
                            <li>
                                <a href="http://www.economy.gov.by/ru/mal-biznes-ru/">
                                    <span>Приз «За вклад в развитие малого и среднего бизнеса Республики Беларусь»</span></a>
                            </li>
                            <li>
                                <a href="https://economy.gov.by/ru/finmsbfond-ru/">
                                    <span>Приз «За личный вклад в поддержку и развитие малого и среднего предпринимательства»</span></a>
                            </li>
                        </ul>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>